language: rust

sudo: false
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - name: "Rust: format check"
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --verbose

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
